<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-nama-profile</name>
   <tag></tag>
   <elementGuidId>7c7aac4f-fe81-4fbd-ad4e-efde35dd3ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'user_name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa2c04cd-3b64-4545-828b-ff25f9e07342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-4 p-3</value>
      <webElementGuid>ed70fd4b-4178-4e02-8b00-d6580feda47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>1056547a-f2ae-4cca-9095-bfcd8350c6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>d224a826-7c16-4480-8d1e-55fe2015aa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d38d756-74b7-444e-8766-05137bd4091e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Najibur Rahman</value>
      <webElementGuid>c5b780b3-d87c-4844-b719-2c78313906df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[name]</value>
      <webElementGuid>c5732a7e-2480-4904-9561-2728bbc1a0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_name</value>
      <webElementGuid>3777cc14-4979-4ae9-b128-1acc4943c594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_name&quot;)</value>
      <webElementGuid>f83e26b2-c2e6-4bf1-af1a-6e1ef3367de2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_name']</value>
      <webElementGuid>ee3c62cd-ab65-4a79-815a-1ff8c1d146a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e7590357-576c-4c30-8ca1-b933d1afcc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nama' and @type = 'text' and @name = 'user[name]' and @id = 'user_name']</value>
      <webElementGuid>13df15c0-8279-4319-b4a7-7a9ad1938c7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
